[tool.poetry]
name = "test-work-actions-poetry"
version = "0.1.0"
description = "test-work-actions-poetry"
authors = ["tokusumi <tksmtoms@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/tokusumi/test-work-actions-poetry"

include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.6"
fastapi = "^0.60.1"
python-jose = "^3.2.0"
requests = "^2.24.0"

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"
pytest-cov = "^2.10.0"
flake8 = "^3.8.3"
mypy = "^0.782"
black = "^19.10b0"
uvicorn = "^0.11.8"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
